namespace DiscordBot.DiscordData
{
    public enum Perk
    {
        NO_BUFF = 0,
        DOUBLE_MORA_LOWER_PRIMOS = 1,
        DOUBLE_MORA = 2,
        DOUBLE_PRIMOS_LOWER_MORA = 3,
        DOUBLE_PRIMOS = 4,
        TWICE_TRAVEL_BOUNTY = 5,
        WELKIN_EREMITE_RECRUIT_ID_WRITE_TWICE = 6,
        WELKIN_EREMITE_RECRUIT_ID_WRITE_TRIPLE_NO_PRIMOS = 7,
        VIP_LIST_NEXT_WELKIN = 8,
        GUARANTEED_NEXT_WELKIN = 9,
        LOWER_TRAVEL_COOLDOWN_DEPEND_TEAM = 10,
        LOWER_TEAPOT_COOLDOWN_DEPEND_TEAM = 11,
        LOWER_TRAVEL_COOLDOWN_PERMANENT = 12,
        LOWER_TEAPOT_COOLDOWN_PERMANENT = 13,
        CHANCE_TO_RESET_COOLDOWN_TRAVEL = 14,
        CHANCE_TO_RESET_COOLDOWN_TRAVEL_BASED_TEAM = 15,
        CHANCE_TO_RESET_COOLDOWN_TEAPOT = 16,
        CHANCE_TO_RESET_COOLDOWN_TEAPOT_BASED_TEAM = 17,
        DOUBLE_CHANCE_TO_RESET_COOLDOWN_TEAPOT_BASED_TEAM = 18,
        DOUBLE_CHANCE_TO_RESET_COOLDOWN_TRAVEL_BASED_TEAM = 19,
        CONVERT_MORA_INTO_PRIMOGEMS_TRAVEL_1TO2 = 20,
        CONVERT_MORA_INTO_PRIMOGEMS_ALL_1TO1 = 21
    }
}